language: SQL

services:
    - postgresql

addons:
    postgresql: "9.6"

before_install:
    - # install postgresql:
    - echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get install wget ca-certificates
    - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
    - sudo apt-get update
    - sudo apt-get upgrade
    - sudo apt-get install postgresql-9.6
    - # install postgis from source:
    - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
    - sudo apt-get --yes install libjson-c-dev postgresql-server-dev-9.6
    - wget http://download.osgeo.org/postgis/source/postgis-2.3.2.tar.gz
    - (mv postgis* /tmp; cd /tmp; tar xzf postgis-2.3.2.tar.gz)
    - (cd /tmp/postgis-2.3.2 ; ./configure; make; sudo make install)

before_script:
    - psql -c 'create database pgmemento_testdb;' -U postgres
    - psql --version

script:
    - psql -U postgres -d pgmemento_testdb -a -f TEST.sql
